name: ember_bot
description: Ember Discord Bot.
version: 0.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  nyxx: ^3.2.1
  nyxx_interactions: ^3.1.0
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.9.0
